title: Sanjana Kaicker
description: Consultant & Future Attorney
baseurl: ""
url: "https://skaicker.github.io"

logo: "/assets/favicon.ico"

# Plugins
plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
# You can keep your current theme here
theme: jekyll-theme-minimal
# Specify the default layout for pages
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
